# Generated by Django 5.0.4 on 2024-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('soltero', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('cumpleaños', models.DateField()),
            ],
        ),
    ]
